import json
import os
import glob

DATA = {
  # ── ATHLETIC ──────────────────────────────────────────────────────────────
  "Jump Squat": ("Explosive squat variation that builds lower body power and speed.", ["Stand with feet shoulder-width apart", "Lower into a squat until thighs are parallel to the floor", "Explode upward and jump as high as possible", "Land softly with bent knees", "Immediately lower into the next rep"]),
  "Bulgarian Pin Squat": ("Single-leg squat with rear foot elevated, targeting quads and glutes.", ["Place rear foot on a bench behind you, front foot forward", "Stand upright with core engaged", "Lower until front thigh is parallel to the floor", "Push through front heel to return to start", "Complete all reps on one side, then switch"]),
  "Split Squat Calf Raises": ("Combines a split squat position with calf raises for lower leg strength.", ["Stand in a split squat stance, front foot forward", "Lower into a split squat position and hold", "Rise up onto the front toes in a calf raise", "Lower the heel back down with control", "Repeat for target reps, then switch sides"]),
  "Boden Walks": ("Walking lunges performed across the floor for leg and glute endurance.", ["Stand upright with feet together", "Step forward with one foot and lower back knee toward the floor", "Keep front knee above ankle and torso upright", "Push off back foot and step into the next lunge", "Continue alternating legs across the floor"]),
  "Sprints": ("Short, all-out running efforts to build speed and cardiovascular power.", ["Warm up with 5 minutes of light jogging", "Drive knees high and pump arms aggressively", "Sprint at 80–100% effort for 20–40 meters", "Walk back to start for recovery", "Repeat 6–10 times"]),
  "Battle Ropes": ("Conditioning exercise using heavy ropes to build power and endurance.", ["Stand with feet shoulder-width apart, slight bend in knees", "Hold one rope end in each hand", "Alternately slam each rope up and down in a wave motion", "Keep core tight and maintain a steady rhythm", "Perform for 20–40 seconds per set"]),
  "Med Ball Slams": ("Explosive full-body movement that develops power and conditions the whole body.", ["Stand with feet shoulder-width apart, hold med ball overhead", "Rise onto toes and brace core", "Slam the ball into the ground as hard as possible", "Catch on the bounce or pick it up", "Repeat for 8–12 reps"]),
  "Med Ball Pushes": ("Power throw that trains explosive upper body and core strength.", ["Stand facing a wall, hold med ball at chest height", "Step forward and explosively push the ball into the wall", "Fully extend both arms at the point of release", "Catch the rebound and immediately reset", "Perform 8–12 explosive reps"]),
  "Sled Pushes": ("Full-body conditioning movement that builds leg drive and work capacity.", ["Load the sled with your desired weight", "Place hands on the handles and lean forward at about 45°", "Drive through your legs in short, powerful steps", "Keep core tight and back flat throughout", "Push 20–40 meters, rest, then repeat"]),
  "Sled Pulls": ("Pulling movement that builds posterior chain strength and conditioning.", ["Attach a harness or rope to the sled", "Face away from the sled and lean forward slightly", "Drive forward with powerful leg steps while the sled follows", "Keep upright posture and engage core", "Pull 20–40 meters, rest, then repeat"]),

  # ── ISOMETRICS ────────────────────────────────────────────────────────────
  "Wall Sit Holds": ("Static lower body hold that builds quad endurance and knee strength.", ["Stand with back flat against a wall", "Slide down until thighs are parallel to the floor", "Keep knees directly above ankles and feet flat", "Hold the position without sliding", "Aim for 30–60 seconds"]),
  "Wall Sit Holds on Toes": ("Wall sit variation with heels raised to increase calf and ankle engagement.", ["Set up in a standard wall sit position", "Rise onto your toes while maintaining the squat angle", "Keep knees above ankles and back flat against the wall", "Hold with weight on the balls of your feet", "Aim for 20–45 seconds"]),
  "Wall Sit Holds on Heels": ("Wall sit variation with toes raised to target the tibialis and anterior shin.", ["Set up in a standard wall sit position", "Lift your toes off the floor, balancing on your heels", "Keep knees above ankles and back flat against the wall", "Maintain heel contact throughout the hold", "Aim for 20–45 seconds"]),
  "Squat Holds": ("Static hold at the bottom of a squat to build quad and hip strength.", ["Stand with feet shoulder-width apart, toes slightly out", "Lower into a deep squat until thighs are parallel or below", "Keep chest up, heels flat, and knees over toes", "Hold the bottom position without bouncing", "Aim for 20–60 seconds"]),
  "ATG Split Squat Holds": ("Deep split squat hold that stretches and strengthens hip flexors and quads.", ["Step one foot forward and lower back knee to the floor", "Sink as deep as possible into the front knee bend", "Keep front shin vertical and torso upright", "Hold the deep position with control", "Aim for 15–30 seconds per side"]),
  "Lunge Holds": ("Static lunge position that challenges quad, glute, and hip flexor strength.", ["Step one foot forward into a lunge stance", "Lower back knee toward the floor without touching it", "Keep front knee above ankle and torso upright", "Hold with both legs engaged", "Aim for 20–40 seconds per side"]),
  "Single Leg Holds": ("Single-leg balance hold to strengthen stabilizers and improve balance.", ["Stand on one leg with a slight bend in the knee", "Lift the opposite foot a few inches off the ground", "Keep hips level and core engaged", "Focus on a fixed point ahead to help balance", "Hold for 30–60 seconds per side"]),
  "Single Leg Holds (Knee Up)": ("Single-leg hold with the free knee raised to hip height for hip flexor engagement.", ["Stand on one leg with a slight bend in the standing knee", "Raise the opposite knee to hip height at 90°", "Keep hips square and core tight", "Hold without letting the raised hip drop", "Aim for 20–40 seconds per side"]),
  "Knee Extension Holds (Band)": ("Isometric quad strengthening using a resistance band at a fixed knee angle.", ["Sit on a bench with a resistance band looped around your ankle", "Extend your leg against the band resistance", "Stop at your chosen angle (e.g., 60° or fully extended)", "Hold with the quad fully contracted", "Aim for 20–40 seconds per side"]),
  "Knee External Rotation Holds": ("Isometric hold that strengthens the hip external rotators.", ["Sit or stand with knees bent at 90°", "Press the knee outward against a fixed resistance (hand or band)", "Keep hips level and spine neutral", "Hold the outward pressure without the knee moving", "Aim for 20–30 seconds per side"]),
  "Knee Internal Rotation Holds": ("Isometric hold that strengthens the hip internal rotators.", ["Sit or stand with knees bent at 90°", "Press the knee inward against a fixed resistance (hand or band)", "Keep hips level and spine neutral", "Hold the inward pressure without the knee moving", "Aim for 20–30 seconds per side"]),
  "Spanish Squat (Band)": ("Band-assisted squat hold that targets the quads with reduced shear force.", ["Loop a resistance band around a fixed post at shin height", "Step back so the band rests against your shins", "Sit back into a squat while the band supports the shins", "Lower until thighs are parallel, keeping torso upright", "Hold for 20–40 seconds"]),
  "Glute Bridge Holds": ("Isometric glute hold at the top of a bridge position.", ["Lie on your back with knees bent and feet flat on the floor", "Drive hips upward by squeezing glutes until body forms a straight line", "Keep core tight and avoid hyperextending the lower back", "Hold the top position with glutes fully contracted", "Aim for 20–40 seconds"]),
  "RDL Holds": ("Isometric hinge hold at the bottom of an RDL to strengthen hamstrings.", ["Stand with feet hip-width apart, holding weights", "Hinge at hips, pushing them back while lowering the weights", "Stop when you feel a strong hamstring stretch (around shin level)", "Keep back flat and a slight bend in the knees", "Hold for 15–30 seconds"]),
  "Single Leg RDL Holds": ("Single-leg hinge hold that challenges hamstrings and hip stabilizers.", ["Stand on one leg with a slight bend in the knee", "Hinge forward at the hip, extending the free leg behind you", "Lower torso until roughly parallel to the floor, keep back flat", "Hold with core tight and hips square", "Aim for 15–30 seconds per side"]),
  "Seated Good Morning Holds": ("Seated isometric hold that strengthens the lower back and hamstrings.", ["Sit on a bench with feet flat on floor", "Hinge forward at the hips, lowering chest toward thighs", "Keep back flat and core braced throughout", "Hold the forward lean position", "Aim for 20–30 seconds"]),
  "Kettlebell Hip Holds": ("Isometric hip hold with a kettlebell to build hip and glute strength.", ["Stand with feet hip-width apart, kettlebell hanging in front", "Hinge slightly at the hips and squeeze glutes to hold the position", "Keep shoulders back and core engaged", "Maintain the partial hinge angle", "Hold for 20–40 seconds"]),
  "Hip Abduction Holds": ("Isometric hold that strengthens the hip abductors and outer glutes.", ["Lie on your side or stand near a wall with a band around your ankles", "Lift or press the top leg outward against the resistance", "Keep hips stacked and core engaged", "Hold the abducted position without rotating the hip", "Aim for 20–30 seconds per side"]),
  "Adductor Holds": ("Isometric inner thigh hold to strengthen the adductors.", ["Lie on your back with knees bent and a ball between your knees", "Squeeze the ball between your knees with maximal force", "Keep lower back flat on the floor", "Hold the squeeze without holding your breath", "Aim for 20–40 seconds"]),
  "Copenhagen Plank": ("Side plank variation with the top leg on a bench, targeting the adductors and core.", ["Place your top foot on a bench and let the bottom leg hang", "Press into a side plank position with your elbow on the floor", "Lift your hips until your body forms a straight line", "Keep core tight and hips elevated", "Hold for 15–30 seconds per side"]),
  "Plank": ("Fundamental core exercise that builds full-body stability and endurance.", ["Start on forearms and toes, elbows directly below shoulders", "Keep body in a straight line from head to heels", "Brace core, squeeze glutes, and breathe steadily", "Avoid letting hips sag or rise", "Hold for 30–60 seconds"]),
  "Side Plank": ("Lateral core exercise that strengthens the obliques and hip stabilizers.", ["Lie on your side with elbow below shoulder", "Stack feet or stagger them for balance", "Lift hips off the floor until body forms a straight line", "Keep core tight and hips elevated throughout", "Hold for 20–40 seconds per side"]),
  "Leg Holds": ("Isometric lower ab exercise performed lying on your back.", ["Lie flat on your back with hands under your lower back", "Raise both legs to about 15 cm above the floor", "Keep lower back pressed into the floor", "Hold the position without letting legs drop", "Aim for 20–40 seconds"]),
  "Scissors": ("Alternating leg movement that targets the lower abs and hip flexors.", ["Lie flat on your back with legs extended", "Raise both legs about 15 cm off the floor", "Alternately cross one leg over the other in a scissors motion", "Keep lower back pressed into the floor throughout", "Perform for 20–40 seconds"]),
  "Biceps Curl Holds": ("Isometric biceps hold at a fixed elbow angle to build static arm strength.", ["Hold a dumbbell with underhand grip, curl to 90°", "Keep elbows close to your sides and upper arms still", "Hold the position while maintaining tension in the biceps", "Breathe steadily, do not hold your breath", "Aim for 20–30 seconds per arm"]),
  "Gewichtsscheibe Halten": ("Weight plate hold that builds grip, shoulder, and forearm endurance.", ["Hold a weight plate at chest height with both hands on the edges", "Keep arms extended or slightly bent", "Engage shoulders and core to maintain the position", "Do not let the plate sag below chest level", "Hold for 20–40 seconds"]),

  # ── KETTLEBELL ────────────────────────────────────────────────────────────
  "Swings": ("Foundational kettlebell movement that develops explosive hip power and posterior chain strength.", ["Stand with feet hip-width apart, kettlebell between feet", "Hinge at hips and grip the kettlebell with both hands", "Hike the kettlebell back between your legs", "Drive hips forward explosively to swing the bell to chest height", "Let it swing back and repeat for 15–20 reps"]),
  "Alternating Swings": ("Single-arm swing variation that adds rotational challenge and grip training.", ["Perform a standard two-handed swing to chest height", "At the top, release with one hand and catch with the other", "Let the bell swing back between your legs", "Drive hips forward and repeat the hand switch each rep", "Perform 10–15 reps per side"]),
  "Side Swings": ("Lateral kettlebell swing that targets the hips and adds rotational power.", ["Stand with feet wider than hip-width apart", "Swing the kettlebell to one side at hip height", "Let it pendulum across to the other side", "Rotate hips slightly in the direction of each swing", "Perform 10–12 reps per side"]),
  "Single Leg Deadlift": ("Unilateral hip hinge with a kettlebell that strengthens hamstrings and balance.", ["Stand on one leg, holding the kettlebell in the opposite hand", "Hinge forward at the hips, extending the free leg behind you", "Lower the kettlebell toward the floor, keeping back flat", "Drive through the standing heel to return upright", "Perform 8–10 reps per side"]),
  "Bob and Wave": ("Dynamic full-body kettlebell movement combining a hinge with a shoulder motion.", ["Stand with feet shoulder-width apart, kettlebell in both hands", "Hinge forward into a partial hip hinge (the bob)", "Add a wave motion with the arms while staying in the hinge position", "Keep core tight and back flat throughout", "Perform for 10–15 reps"]),
  "Lunge + Alternating Presses": ("Combines a lunge with an overhead press to train full-body coordination and strength.", ["Hold a kettlebell in one hand at shoulder height", "Step into a lunge with the opposite leg forward", "As you lower into the lunge, press the kettlebell overhead", "Return to standing as you lower the bell", "Alternate sides for 8–10 reps per side"]),
  "Racked Squat": ("Squat with kettlebell in rack position that challenges core stability and leg strength.", ["Hold the kettlebell in rack position (resting on forearm, elbow tucked)", "Stand with feet shoulder-width apart, toes slightly out", "Lower into a squat keeping the bell stable and torso upright", "Drive through heels to return to standing", "Perform 8–12 reps per side"]),
  "Goblet Squat": ("Front-loaded squat holding the kettlebell at chest height for depth and posture.", ["Hold kettlebell by the horns at chest height", "Stand with feet slightly wider than hip-width, toes out", "Lower into a deep squat keeping elbows inside your knees", "Keep chest up and heels flat on the floor", "Drive through heels to stand — 10–15 reps"]),
  "Dual Front Squat": ("Double kettlebell front squat for increased load and upper back engagement.", ["Clean two kettlebells into rack position at shoulder height", "Stand with feet shoulder-width apart", "Lower into a deep squat keeping bells stable in rack", "Drive through heels to return to standing", "Perform 6–10 reps"]),
  "Lunge": ("Kettlebell lunge that adds load for greater leg and glute development.", ["Hold a kettlebell in each hand hanging at sides or one in rack position", "Step one foot forward and lower back knee toward the floor", "Keep front knee above ankle and torso upright", "Push through front heel to return to start", "Perform 8–12 reps per side"]),
  "Alternating Lunges": ("Alternating forward lunges with kettlebell for leg endurance and balance.", ["Hold a kettlebell in each hand hanging at sides", "Step forward with one leg into a lunge", "Lower until back knee nearly touches the floor", "Push back to standing and immediately lunge with the other leg", "Continue alternating for 10–12 reps per side"]),
  "Side Lunges": ("Lateral lunge with kettlebell that targets inner thighs and glutes.", ["Hold kettlebell at chest height or hanging in front", "Step wide to one side, bending the stepping knee", "Lower hips toward the floor while keeping the other leg straight", "Push off the bent leg to return to center", "Perform 8–10 reps per side"]),
  "Reverse Lunge Swings": ("Combines a reverse lunge with a kettlebell swing for power and coordination.", ["Start standing with kettlebell in both hands", "Step back into a reverse lunge as you hike the bell between your legs", "Drive the front foot into the floor and extend the hip to come out of the lunge", "Use the hip drive to swing the bell to chest height", "Alternate legs for 8–10 reps per side"]),
  "Lunges Around the World": ("Full lunge circuit covering forward, lateral, and reverse directions.", ["Hold kettlebells at sides", "Lunge forward with one leg and return to center", "Lunge to the side with the same leg and return to center", "Lunge backward with the same leg and return to center", "Complete all directions on one side, then switch — 3 rounds per side"]),
  "Wood Chopper Lunges": ("Lunge combined with a rotational wood chop for full-body movement.", ["Hold a kettlebell with both hands above one shoulder", "Step into a lunge as you bring the bell diagonally to the opposite hip", "Keep core engaged and rotate through the torso", "Return to standing as you raise the bell back overhead", "Perform 8–10 reps per side"]),
  "Clean Arm Press": ("Two-phase kettlebell movement combining a clean and a press for power and strength.", ["Hinge at hips with kettlebell between legs", "Drive hips forward and pull the bell into rack position (the clean)", "From rack, press the bell overhead until arm is fully extended", "Lower back to rack, then to starting position", "Perform 6–8 reps per side"]),
  "Horizontal Presses": ("Horizontal pushing exercise with kettlebells to develop chest and triceps.", ["Lie on a bench or floor holding a kettlebell in each hand at chest level", "Start with elbows at about 45° from the body", "Press both bells straight up until arms are extended", "Lower with control back to chest level", "Perform 8–12 reps"]),
  "Shoulder Presses": ("Overhead press with kettlebell for shoulder and upper body strength.", ["Hold kettlebell in rack position at shoulder height", "Brace core and keep elbow tucked below the bell", "Press the bell straight overhead until arm is fully extended", "Lower slowly back to rack position", "Perform 8–10 reps per side"]),
  "Pullovers": ("Lying pullover with kettlebell that stretches the chest and strengthens the lats.", ["Lie on a bench with head near the edge, holding kettlebell above chest", "Keeping arms slightly bent, lower the bell behind your head", "Feel the stretch across chest and lats", "Pull the bell back over chest to starting position", "Perform 10–12 reps"]),
  "Rows": ("Single-arm kettlebell row that builds upper back and bicep strength.", ["Place one hand and knee on a bench for support", "Hold kettlebell in the other hand, arm extended toward floor", "Pull the bell toward your hip, driving elbow back", "Keep back flat and avoid rotating the torso", "Lower with control — 8–12 reps per side"]),
  "Upright Rows": ("Vertical pull targeting the upper traps and side deltoids.", ["Stand holding the kettlebell with both hands in front of thighs", "Pull the bell straight up along your body toward your chin", "Lead with your elbows, keeping them above wrist level", "Lower with control back to starting position", "Perform 10–12 reps"]),
  "Side Front Raises": ("Combination of lateral and front raises to develop shoulder endurance.", ["Stand holding a kettlebell in each hand at sides", "Raise one arm to the side and the other to the front simultaneously", "Lift to shoulder height with a slight elbow bend", "Lower with control and alternate arms", "Perform 10–12 reps per side"]),
  "Rotation": ("Kettlebell rotation exercise that develops core rotational strength.", ["Stand with feet shoulder-width apart, holding kettlebell at chest", "Rotate the torso to one side, bringing the bell along", "Keep hips square and feet flat on the floor", "Return to center and rotate to the other side", "Perform 10–12 reps per side"]),
  "Windmills": ("Complex movement that develops shoulder stability, hip mobility, and core strength.", ["Press kettlebell overhead with one arm, feet shoulder-width apart", "Turn feet 45° away from the arm holding the bell", "Hinge sideways at the hip, lowering the free hand toward the floor", "Keep eyes on the kettlebell throughout", "Return to standing — 5–8 reps per side"]),
  "Uppercuts": ("Boxing-inspired kettlebell movement that trains rotational power and shoulder strength.", ["Stand in a slight squat stance, holding a kettlebell in one hand", "Drive the bell upward in an uppercut arc, rotating through the hips", "Let hips and core generate the power, not just the arm", "Control the bell back to starting position", "Perform 10–12 reps per side"]),
  "Helos": ("Circular overhead kettlebell movement that challenges shoulder stability and core control.", ["Press the kettlebell overhead with one arm", "Move the bell in a controlled circle overhead (halo motion)", "Keep the shoulder packed and core braced", "Complete 5 circles in one direction, then reverse", "Perform per side with fully controlled movement"]),
  "Kniend Pushout Rotate": ("Kneeling kettlebell push-and-rotate exercise for core anti-rotation strength.", ["Kneel on one knee, holding kettlebell at chest with both hands", "Push the bell straight out in front with arms extended", "Rotate the bell to the left then to the right while arms stay extended", "Return to chest and repeat", "Perform 8–10 reps per side"]),

  # ── KRAFT ─────────────────────────────────────────────────────────────────
  "Squats": ("Fundamental lower body exercise targeting quads, glutes, and hamstrings.", ["Stand with feet shoulder-width apart, toes slightly out", "Brace core and push hips back as you lower down", "Lower until thighs are parallel to the floor or deeper", "Keep chest up and heels flat on the floor", "Drive through heels to return to standing — 8–12 reps"]),
  "Lunges": ("Unilateral leg exercise for quad, glute, and balance development.", ["Stand with feet together, hands on hips or holding weights", "Step one foot forward and lower back knee toward the floor", "Keep front knee above ankle and torso upright", "Push off front foot to return to starting position", "Alternate legs for 10–12 reps per side"]),
  "ATG Split Squats": ("Deep range split squat reaching full hip and knee flexion for maximum leg development.", ["Step one foot forward into a lunge stance", "Lower the back knee all the way to the floor", "Lean the front shin forward to maximize depth", "Drive through front foot to return to start", "Perform 8–10 reps per side"]),
  "Split Squats": ("Stationary lunge that isolates each leg individually for strength and balance.", ["Stand in a split stance with one foot forward, one back", "Lower straight down by bending both knees", "Keep front knee tracking over the toes", "Drive through front heel to return to start", "Perform 8–12 reps per side"]),
  "RDL's": ("Hip hinge movement targeting the hamstrings and glutes with a slight knee bend.", ["Stand with feet hip-width apart, holding weights in front of thighs", "Push hips back and lower the weights along your legs", "Stop when you feel a strong hamstring stretch", "Keep back flat and a slight bend in the knees", "Drive hips forward to return — 8–12 reps"]),
  "Single Leg RDL's": ("Single-leg hip hinge that challenges balance while targeting hamstrings and glutes.", ["Stand on one leg with a slight bend in the knee", "Hinge forward at the hip, extending the free leg behind for balance", "Lower weight toward the floor while keeping back flat", "Return to standing by driving through the heel", "Perform 8–10 reps per side"]),
  "Tibialis Raises": ("Isolation exercise for the tibialis anterior (shin muscle) to prevent shin splints.", ["Stand with heels on a step or against a wall", "Lift the front of your feet (toes toward shins) as high as possible", "Hold briefly at the top, then lower with control", "Keep legs straight throughout the movement", "Perform 15–20 reps"]),
  "Leg Curls": ("Machine or band exercise that isolates the hamstrings.", ["Lie face down on a leg curl machine with ankles under the pad", "Curl both legs up toward your glutes", "Squeeze hamstrings at the top", "Lower with control back to start", "Perform 10–15 reps"]),
  "Leg Extension": ("Quad isolation exercise performed on a machine.", ["Sit on a leg extension machine with ankles behind the pad", "Extend both legs until straight, contracting the quads", "Hold briefly at the top", "Lower with control back to start", "Perform 10–15 reps"]),
  "Calf Raises": ("Isolation exercise for the calves to build lower leg strength and size.", ["Stand with the balls of your feet on an elevated surface", "Lower heels as far as possible for a full stretch", "Drive up onto your toes as high as possible", "Hold at the top for a brief squeeze", "Perform 15–20 reps"]),
  "Romanian Deadlift": ("Hip hinge movement targeting the hamstrings and lower back.", ["Stand with feet hip-width apart, barbell or dumbbells in front", "Hinge at hips keeping back flat and bar close to legs", "Lower until a strong stretch is felt in the hamstrings", "Drive hips forward to return to standing", "Perform 8–12 reps"]),
  "Single Leg Step Ups": ("Unilateral step-up onto a box to develop quad and glute strength.", ["Stand in front of a sturdy box or step", "Place one foot fully on the box", "Drive through that heel to lift your body onto the box", "Step back down with control", "Perform 10–12 reps per side"]),
  "Lat Pull Downs": ("Cable exercise that builds upper back width by training the latissimus dorsi.", ["Sit at a lat pulldown machine, grip bar wider than shoulder-width", "Lean slightly back and pull the bar down to upper chest level", "Squeeze shoulder blades together at the bottom", "Extend arms slowly to return to start", "Perform 10–12 reps"]),
  "Rows Tief": ("Low horizontal row targeting the middle and lower back.", ["Sit at a cable row station, grip the handle with both hands", "Keep back straight and pull handle toward your lower abdomen", "Drive elbows back and squeeze shoulder blades together at the end", "Extend arms with control to return to start", "Perform 10–12 reps"]),
  "Rows Hoch": ("High horizontal row targeting the upper back and rear deltoids.", ["Stand or sit at a cable station set at upper chest height", "Pull the handle toward your upper chest or chin", "Keep elbows flared out to shoulder height", "Squeeze upper back at the end of the pull", "Perform 10–12 reps"]),
  "Reverse Butterflies": ("Rear delt isolation targeting the back of the shoulders and upper back.", ["Sit at a pec deck machine facing inward, or hinge forward holding dumbbells", "Start with arms forward, slight bend at elbows", "Pull arms back in a wide arc out to the sides", "Squeeze rear delts and upper back at the end", "Return slowly to start — 12–15 reps"]),
  "Back Extension": ("Lower back extension exercise that strengthens the erector spinae and glutes.", ["Position yourself face-down on a back extension bench", "Start with torso hanging down at about 90°", "Raise torso by extending the lower back until body is straight", "Squeeze glutes at the top, do not hyperextend", "Lower with control — 12–15 reps"]),
  "Flies": ("Chest isolation exercise using a wide arc to stretch and squeeze the pecs.", ["Lie on a bench holding dumbbells above chest, palms facing each other", "Lower arms out to the sides in a wide arc with a slight elbow bend", "Feel the stretch across the chest at the bottom", "Bring arms back together in the same arc, squeezing chest", "Perform 12–15 reps"]),
  "Incline Flies Low Chest": ("Incline dumbbell fly targeting the lower portion of the chest.", ["Set bench to a slight incline (15–30°)", "Hold dumbbells above chest with a slight elbow bend", "Lower arms out to the sides in a wide arc", "Focus on feeling the stretch in the lower chest", "Bring arms back together overhead — 12–15 reps"]),
  "Decline Chest Press": ("Pressing movement on a decline bench targeting the lower chest.", ["Lie on a decline bench with feet secured", "Hold dumbbells or barbell at chest level, elbows at 45°", "Press the weight upward until arms are extended", "Lower with control to chest level", "Perform 8–12 reps"]),
  "Dumbbell Chest Press": ("Classic pressing movement targeting the chest, shoulders, and triceps.", ["Lie flat on a bench holding a dumbbell in each hand at chest level", "Press both dumbbells upward until arms are fully extended", "Keep a slight bend in elbows at the top", "Lower with control, feeling the chest stretch at the bottom", "Perform 8–12 reps"]),
  "Bankdrücken": ("Barbell bench press — the fundamental compound chest exercise.", ["Lie on a flat bench with eyes below the bar", "Grip bar slightly wider than shoulder-width", "Unrack and lower bar to mid-chest with control", "Press bar back up to starting position", "Perform 5–8 reps — use a spotter with heavy weight"]),
  "Gewichtsscheibe Press": ("Chest press with a weight plate to build grip strength and chest power.", ["Lie on a bench holding a weight plate at chest with both hands on the edges", "Press the plate directly upward until arms are extended", "Keep hands flat against the plate throughout", "Lower with control back to chest level", "Perform 12–15 reps"]),
  "Overhead Chest Curls": ("Overhead dumbbell movement that targets the upper chest.", ["Lie on a bench with dumbbells extended overhead", "Lower the weights in a curling arc toward the top of your head", "Keep arms parallel, feel the upper chest engage", "Curl weights back to overhead position", "Perform 12–15 reps"]),
  "Lateral Raises": ("Shoulder isolation targeting the medial deltoid for shoulder width.", ["Stand holding dumbbells at sides, slight bend in elbows", "Raise both arms to the sides until they reach shoulder height", "Keep wrists neutral and avoid shrugging", "Lower with control back to sides", "Perform 12–15 reps"]),
  "Shoulder Press": ("Overhead pressing movement for overall shoulder and upper body strength.", ["Hold dumbbells or barbell at shoulder height, palms facing forward", "Brace core and press weights straight overhead", "Fully extend arms at the top", "Lower with control back to shoulder level", "Perform 8–12 reps"]),
  "Shoulder Front Raises": ("Anterior deltoid isolation using a forward raise motion.", ["Stand holding dumbbells at sides, palms facing back", "Raise both arms straight forward to shoulder height", "Keep a slight bend in the elbows and avoid swinging", "Lower with control", "Perform 12–15 reps"]),
  "Shoulder Pulls": ("Horizontal pulling movement targeting rear delts and upper back.", ["Hold a resistance band or cable at shoulder height", "Pull toward your face, spreading hands apart", "Drive elbows back and squeeze rear delts", "Return slowly to starting position", "Perform 12–15 reps"]),
  "Reverse Fly": ("Bent-over fly that isolates the rear deltoid and upper back.", ["Stand with a slight forward lean, dumbbells hanging below chest", "Raise both arms out to the sides in a wide arc", "Keep a slight bend in the elbows and lead with the elbows", "Squeeze rear delts at the top", "Lower with control — 12–15 reps"]),
  "Shoulder Shrugs": ("Trap isolation exercise to build upper trapezius size and strength.", ["Stand holding dumbbells or barbell at sides", "Shrug both shoulders straight up toward your ears", "Hold briefly at the top, fully contracting the traps", "Lower with control, fully stretching the traps", "Perform 12–15 reps"]),
  "Upright Rows": ("Vertical pull targeting the upper traps and side deltoids.", ["Stand holding dumbbells or barbell in front of thighs", "Pull weight straight up along your body toward the chin", "Lead with your elbows, keeping them above the wrists", "Do not pull higher than the chin", "Lower with control — 10–12 reps"]),
  "Crunches": ("Classic ab exercise that targets the rectus abdominis.", ["Lie on your back with knees bent, feet flat, hands behind head", "Brace core and curl head and shoulders off the floor", "Exhale at the top, do not pull on your neck", "Lower with control back to start", "Perform 15–20 reps"]),
  "Planks": ("Full-body isometric hold that builds core stability and endurance.", ["Start on forearms and toes, elbows below shoulders", "Keep body in a straight line from head to heels", "Brace core, squeeze glutes, breathe steadily", "Avoid letting hips sag or rise", "Hold for 30–60 seconds"]),
  "Leg Raises": ("Lower ab exercise performed by raising straight legs from lying position.", ["Lie flat on your back with legs extended", "Place hands under your lower back for support", "Raise both legs to 90° keeping lower back pressed down", "Lower legs slowly back toward the floor without touching", "Perform 12–15 reps"]),
  "Flutter Kicks": ("Alternating leg movement targeting the lower abs and hip flexors.", ["Lie flat on your back with legs extended, hands under glutes", "Raise both legs a few centimetres off the floor", "Rapidly alternate kicking each leg up and down in small motions", "Keep lower back pressed into the floor", "Perform for 20–30 seconds"]),
  "Side Crunches": ("Oblique-targeting crunch variation performed from a side-lying position.", ["Lie on your side with legs stacked", "Place top hand behind your head", "Crunch sideways, lifting head and shoulder off the floor", "Squeeze obliques at the top", "Lower with control — 15 reps per side"]),
  "Curls": ("Classic bicep curl for building arm size and elbow flexor strength.", ["Stand holding dumbbells at sides with palms facing forward", "Curl both weights toward your shoulders by bending at the elbow", "Squeeze biceps at the top", "Lower with control back to starting position", "Perform 10–12 reps"]),
  "Wrist Curls": ("Wrist flexor exercise to strengthen forearms and improve grip.", ["Sit with forearms resting on thighs, palms facing up, holding weights", "Lower the weight by extending wrists toward the floor", "Curl wrists upward as far as possible", "Keep forearms flat on thighs throughout", "Perform 15–20 reps"]),
  "Wrist Extension": ("Wrist extensor exercise for forearm balance and injury prevention.", ["Sit with forearms on thighs, palms facing down, holding weights", "Lower weights by bending wrists toward the floor", "Extend wrists upward as far as possible", "Keep forearms flat on thighs throughout", "Perform 15–20 reps"]),
  "Hammer Curls": ("Neutral-grip curl targeting the brachialis and brachioradialis alongside biceps.", ["Stand holding dumbbells at sides, palms facing inward", "Curl both weights toward shoulders with a neutral grip", "Keep elbows close to sides and avoid swinging", "Lower with control", "Perform 10–12 reps"]),
  "Spider Curls": ("Incline bench bicep curl that eliminates momentum for strict isolation.", ["Lie chest-down on a 45° incline bench", "Let arms hang straight down, holding dumbbells", "Curl the weights toward your face, bending only at the elbows", "Squeeze biceps at the top", "Lower with full extension — 10–12 reps"]),
  "Preacher Curls": ("Bicep curl on a preacher bench for strict form and peak contraction.", ["Sit at a preacher bench with upper arms resting on the pad", "Hold a barbell or dumbbell with underhand grip", "Curl the weight toward your chin without lifting arms off the pad", "Squeeze at the top, then lower fully", "Perform 10–12 reps"]),
  "Tricep Push Downs": ("Cable exercise for tricep isolation by pushing the attachment downward.", ["Stand at a cable machine with rope or bar attachment at head height", "Grip with both hands, elbows tucked at sides", "Push the attachment down until arms are fully extended", "Squeeze triceps at the bottom, then return slowly", "Perform 12–15 reps"]),
  "Single Arm Push Downs": ("Unilateral cable push-down to isolate each tricep individually.", ["Stand at a cable machine with a single handle attachment", "Grip with one hand, elbow tucked at your side", "Push down until arm is fully extended", "Squeeze tricep at the bottom and return slowly", "Perform 12–15 reps per side"]),
  "Single Arm Triceps Extension": ("Overhead single-arm extension for full tricep stretch and contraction.", ["Hold a dumbbell in one hand overhead with arm extended", "Bend elbow to lower the dumbbell behind your head", "Keep upper arm stationary and close to your head", "Extend arm back overhead to full extension", "Perform 10–12 reps per side"]),
  "Samurai Extensions": ("Two-handed overhead tricep extension for full tricep stretch and contraction.", ["Hold a single dumbbell with both hands overhead", "Lower the dumbbell behind your head by bending both elbows", "Keep elbows close together and pointing forward", "Extend arms back overhead to full lockout", "Perform 12–15 reps"]),
  "African Curls": ("Bicep curl variation with a rotating wrist motion for full muscle engagement.", ["Stand holding dumbbells at sides, palms facing back", "Curl the weight up while rotating wrists outward (supinating)", "End with palms facing up at the top of the curl", "Lower with control, rotating back to starting position", "Perform 10–12 reps"]),

  # ── MOBILITY ──────────────────────────────────────────────────────────────
  "Butterfly": ("Hip-opening stretch targeting the inner thighs and hip flexors.", ["Sit on the floor and bring the soles of your feet together", "Let knees drop out to the sides", "Hold your feet and sit tall with a straight back", "Gently press knees toward the floor", "Hold for 30–60 seconds"]),
  "Butterfly Holds": ("Isometric hold at the butterfly position to deepen the hip-opening stretch.", ["Sit in butterfly position with soles of feet together", "Place hands on knees and gently press them toward the floor", "Hold at the point of mild resistance", "Breathe steadily and relax into the position", "Hold for 30–60 seconds"]),
  "Couch Stretch": ("Hip flexor and quad stretch performed against a wall or couch.", ["Kneel with one shin against a wall or couch behind you", "Step the other foot forward into a lunge position", "Drive hips forward and upright until you feel the hip flexor stretch", "Keep torso tall and core lightly engaged", "Hold for 60–90 seconds per side"]),
  "Wrist Circles": ("Mobility drill for the wrists to improve range of motion and joint health.", ["Extend arms in front at shoulder height", "Make a loose fist with both hands", "Rotate wrists in large circles — 10 rotations clockwise", "Reverse direction for 10 rotations counter-clockwise", "Repeat 2–3 times"]),
  "Cobra": ("Spinal extension stretch that opens the chest and stretches the abs.", ["Lie face down with hands under shoulders, elbows bent", "Press palms into the floor and lift your chest up", "Keep hips on the floor and elbows slightly bent", "Look straight ahead and relax the lower back", "Hold for 20–30 seconds"]),
  "Cat Cow": ("Spinal mobility drill alternating between flexion and extension.", ["Start on hands and knees, wrists below shoulders, knees below hips", "Inhale and drop belly toward floor, lifting head and tailbone (Cow)", "Exhale and round spine toward the ceiling, tucking chin and pelvis (Cat)", "Move fluidly between the two positions", "Repeat for 10–15 slow reps"]),
  "Child Pose": ("Resting stretch that opens the hips and releases lower back tension.", ["Kneel on the floor and sit back toward your heels", "Reach arms forward and lower your forehead to the floor", "Let the chest sink toward the floor", "Breathe deeply into the back", "Hold for 30–60 seconds"]),
  "90-90 Stretch": ("Hip mobility drill targeting internal and external rotation in both hips.", ["Sit with both knees bent at 90° — one leg in front, one to the side", "Keep torso upright and both sit bones on the floor", "Lean gently forward over the front shin to feel the stretch", "Hold for 30–45 seconds, then switch sides", "Repeat 2–3 times per side"]),
  "Seated Good Mornings": ("Seated forward fold targeting hamstring flexibility and lower back mobility.", ["Sit on the floor with legs extended straight in front", "Sit tall and brace core lightly", "Hinge forward at the hips, reaching hands toward your feet", "Keep back as flat as possible", "Hold for 30–60 seconds"]),

  # ── PLYOMETRICS ───────────────────────────────────────────────────────────
  "Pogo Jumps": ("Rapid small hops on the spot to train ankle stiffness and reactive strength.", ["Stand with feet hip-width apart, slight bend in knees", "Jump using only ankle and calf spring — minimal knee bend", "Land and immediately jump again with minimal ground contact time", "Keep torso upright and arms relaxed", "Perform 20–30 reps"]),
  "Bounce Jumps": ("Moderate-height jumps focusing on elastic energy and landing mechanics.", ["Stand with feet shoulder-width apart", "Load the hips slightly and jump upward", "Land softly with bent knees to absorb impact", "Immediately use the elastic rebound to jump again", "Perform 10–15 reps"]),
  "Box Jumps": ("Explosive jump onto a box to develop lower body power and landing control.", ["Stand facing a sturdy box (30–60 cm)", "Swing arms back and bend knees to load the jump", "Explode upward and forward to land on the box with both feet", "Land softly with bent knees in an athletic position", "Step back down and repeat — 5–8 reps"]),
  "Seated Jumps": ("Jump from a seated position to eliminate the stretch reflex and test raw power.", ["Sit on a box with hips at 90°, feet flat on floor", "Without rocking forward, drive through feet and jump upward", "Extend hips, knees, and ankles fully at takeoff", "Land softly with bent knees", "Reset and repeat — 5–8 reps"]),
  "Explosive Squats": ("Squat variation with a powerful upward drive to build lower body power.", ["Stand with feet shoulder-width apart", "Lower into a squat until thighs are parallel", "Explode upward with maximum force through legs and hips", "Land softly or stop at the top with full intent", "Perform 6–10 reps with full effort"]),
  "Split Jumps": ("Plyometric lunge jump that switches legs in the air for power and coordination.", ["Start in a lunge position with one foot forward", "Jump upward explosively, switching leg positions in the air", "Land in the opposite lunge position, absorbing impact softly", "Immediately jump again to switch back", "Perform 8–12 reps per side"]),
  "Explosive Leg Switching": ("Rapid alternating leg switches that develop speed and lower body power.", ["Stand on one leg with the other raised, hip at 90°", "Explosively switch legs, driving the raised knee down and the other knee up", "Minimize ground contact time between switches", "Stay light on your feet and keep core tight", "Perform for 20–30 seconds"]),
  "Depth Drops": ("Step off a box and land softly to train impact absorption and stiffness.", ["Stand on a box (30–50 cm), toes at the edge", "Step off (do not jump) and drop to the floor", "Land with both feet simultaneously, absorbing with bent knees", "Focus on a quiet, controlled landing", "Perform 5–8 reps"]),
  "Broad Jumps": ("Horizontal jump for maximum distance to train triple extension and power.", ["Stand with feet shoulder-width apart", "Load hips back and swing arms behind", "Explode forward and upward, swinging arms forward for momentum", "Land with both feet, soft knees in a balanced position", "Perform 5–8 reps"]),
  "Tuck Jumps": ("Explosive jump pulling knees to chest at peak height to develop power and coordination.", ["Stand with feet hip-width apart", "Jump as high as possible, pulling both knees toward the chest at the top", "Release legs to land softly with bent knees", "Absorb the landing and immediately repeat", "Perform 8–10 reps"]),
  "Burpees": ("Full-body conditioning movement combining a squat, plank, push-up, and jump.", ["Stand, then squat down and place hands on the floor", "Jump or step feet back into a push-up position", "Perform a push-up (optional)", "Jump or step feet back to your hands and stand up", "Jump with arms overhead to complete one rep — 10–15 reps"]),
  "Side Jumps": ("Lateral jumps over a line to build lateral power and landing stability.", ["Stand on one side of a line or low obstacle", "Jump laterally to the other side with both feet", "Land softly with bent knees and immediately jump back", "Keep a short, reactive ground contact time", "Perform 10 reps per side"]),
  "Skater Jumps": ("Single-leg lateral jumps mimicking a speed skater to build lateral power.", ["Stand on one leg", "Explode laterally to the other side, landing on the opposite single leg", "Allow the trail leg to swing behind for balance", "Absorb the landing and immediately push off to the other side", "Perform 10–12 reps per side"]),
  "Single Leg Jumps": ("Unilateral jump to develop single-leg power and landing stability.", ["Stand on one leg with a slight knee bend", "Load the hip and jump upward as high as possible", "Land on the same leg with a soft knee bend", "Stabilize before the next rep", "Perform 5–8 reps per side"]),
  "Lunge Jumps Alternating": ("Alternating plyometric lunges with an explosive jump between each rep.", ["Start in a lunge position with one foot forward", "Jump upward and switch legs in the air", "Land in the opposite lunge position, absorbing softly", "Immediately explode up to switch again", "Perform 10–12 reps per side"]),
  "Bounding": ("Exaggerated running strides covering maximum distance per step to build elastic power.", ["Begin with a short jog to build momentum", "Push off one leg with maximum force, reaching forward with the opposite leg", "Aim for as much distance as possible per stride", "Land on the opposite foot and continue in a bounding pattern", "Perform for 20–30 meters per set"]),
  "Heel Walks": ("Walking on heels to strengthen the tibialis anterior and improve dorsiflexion.", ["Stand tall and lift toes off the ground", "Walk forward on your heels for 20–30 meters", "Take small, controlled steps keeping balance", "Keep core engaged and torso upright", "Rest and repeat 2–3 times"]),
  "Toe Walks": ("Walking on tiptoes to strengthen the calves and improve ankle plantar flexion.", ["Rise onto the balls of your feet", "Walk forward on your tiptoes for 20–30 meters", "Take small, controlled steps", "Keep core engaged and torso upright", "Rest and repeat 2–3 times"]),
  "Ankle Hops": ("Small rapid hops using only ankles to strengthen the calves and Achilles tendon.", ["Stand with feet hip-width apart", "Hop in place using only your ankles — keep knees mostly straight", "Land on the balls of your feet and immediately hop again", "Keep ground contact time as short as possible", "Perform 20–30 rapid hops"]),
  "Explosive Pushups": ("Push-up with explosive power, pushing up fast enough to briefly leave the floor.", ["Start in standard push-up position", "Lower chest to the floor under control", "Explode upward with maximum force, pushing hands off the floor", "Land softly and immediately lower into the next rep", "Perform 5–10 reps"]),
  "Clap Pushups": ("Push-up with a mid-air clap to develop upper body power and coordination.", ["Start in standard push-up position", "Lower chest to the floor with control", "Explode upward with enough power to clap hands mid-air", "Catch yourself with soft elbows and lower for the next rep", "Perform 5–8 reps"]),
  "Med Ball Chest Pass": ("Standing chest throw against a wall to develop upper body explosive power.", ["Stand 1–2 meters from a wall holding med ball at chest", "Step forward and explosively push the ball into the wall", "Fully extend both arms at the point of release", "Catch the rebound and immediately reset", "Perform 8–12 reps"]),
  "Med Ball Slam": ("Full-body explosive throw of a med ball into the ground for power and conditioning.", ["Stand with feet shoulder-width apart, med ball overhead", "Rise onto toes and brace core", "Slam the ball into the ground with maximum force", "Catch on the bounce or pick it up", "Repeat for 8–12 reps"]),

  # ── ROTATION ──────────────────────────────────────────────────────────────
  "Russian Twists": ("Seated rotational core exercise targeting the obliques and deep core muscles.", ["Sit with knees bent and lean back to about 45°", "Hold a weight at chest level with both hands", "Rotate torso to one side, touching the weight toward the floor", "Rotate to the other side to complete one rep", "Perform 20 total reps (10 per side)"]),
  "Trunk Rotation": ("Standing core rotation drill for spinal mobility and rotational strength.", ["Stand with feet shoulder-width apart, arms crossed or holding a stick", "Rotate upper body to one side while keeping hips facing forward", "Return to center and rotate to the other side", "Control the movement, do not bounce at end range", "Perform 15–20 reps per side"]),
  "Alternating Plate Turns": ("Standing plate rotation that develops core anti-rotation and rotational power.", ["Stand with feet shoulder-width apart, holding a weight plate at chest", "Rotate to one side, extending arms straight out", "Return to center and rotate to the other side", "Keep hips facing forward and rotate only the torso", "Perform 12–15 reps per side"]),
  "Cable Woodchop": ("Diagonal cable pull from high to low that builds rotational core power.", ["Set cable at high position and stand sideways to the machine", "Grip the handle with both hands above the shoulder", "Pull the cable diagonally across the body to the opposite hip", "Keep arms relatively straight and rotate through the core", "Perform 10–12 reps per side"]),
  "Med Ball Throws Alternating": ("Alternating rotational throws against a wall to build explosive core power.", ["Stand sideways to a wall, holding a med ball at hip level", "Rotate away from the wall to load up", "Rotate back explosively and throw the ball into the wall", "Catch the rebound and immediately set up the next throw", "Perform 10 reps per side"]),
  "Shoulder Back Rotation": ("Rotational shoulder mobility drill to improve thoracic rotation and posture.", ["Stand or sit upright with arms extended to the sides at shoulder height", "Rotate one arm forward and the other backward simultaneously", "Keep core stable and movement controlled", "Alternate directions fluidly", "Perform 10–15 reps per side"]),
}

exercises_dir = os.path.join(os.path.dirname(__file__), '../data/exercises')
updated_total = 0
missing_all = []

for filepath in sorted(glob.glob(os.path.join(exercises_dir, '*.json'))):
    with open(filepath, 'r') as f:
        exercises = json.load(f)

    updated = 0
    for ex in exercises:
        name = ex['name']
        if name in DATA:
            ex['description'] = DATA[name][0]
            ex['instructions'] = list(DATA[name][1])
            updated += 1
        else:
            missing_all.append(name)

    with open(filepath, 'w') as f:
        json.dump(exercises, f, ensure_ascii=False, indent=2)

    print(f"{os.path.basename(filepath)}: updated {updated}/{len(exercises)}")
    updated_total += updated

print(f"\nTotal updated: {updated_total}")
if missing_all:
    print(f"Not found in DATA ({len(missing_all)}): {missing_all}")
